//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagageSortering.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BagageSortering.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirportName,Country,AirportCode
        ///Vienna,Austria,VIE
        ///Baku,Azerbaijan,GYD
        ///Minsk,Belarus,MSQ
        ///Antwerp,Belgium,ANR
        ///Brussels,Belgium,BRU
        ///Charleroi,Belgium,CRL
        ///Liege,Belgium,LGG
        ///Ostend Bruges,Belgium,OST
        ///Sarajevo,Bosnia and Herzegovina,SJJ
        ///Tuzla,Bosnia and Herzegovina,TZL
        ///Burgas,Bulgaria,BOJ
        ///Sofia,Bulgaria,SOF
        ///Varna,Bulgaria,VAR
        ///Dubrovnik,Croatia,DBV
        ///Pula,Croatia,PUY
        ///Split,Croatia,SPU
        ///Zadar,Croatia,ZAD
        ///Zagreb,Croatia,ZAG
        ///Larnaca,Cyprus,LCA
        ///Paphos,Cyprus,PFO
        ///Brno,Czech Republic,BRQ
        ///Prague,Czech [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GateNr,Terminal
        ///D1,1
        ///D2,1
        ///D3,1
        ///D4,1
        ///D5,1
        ///D6,1
        ///D7,1
        ///D8,1
        ///B1,2
        ///B2,2
        ///B3,2
        ///B4,2
        ///B5,2
        ///B6,2
        ///B7,2
        ///B8,2.
        /// </summary>
        internal static string AirportTerminalGates {
            get {
                return ResourceManager.GetString("AirportTerminalGates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID,Prefix,Name,LogoFileName
        ///1,AZ,Alitalia,Alitalia.jpg
        ///2,FR,RyanAir,RyanAir.png
        ///3,AC,Air Canada,AirCanada.png
        ///4,AS,Alaska Airlines,Alaska.png
        ///5,EK,Emirates,Emirates.png
        ///6,JL,Japan Airlines,Japan.png
        ///7,LH,Lufthansa,Lufthansa.png
        ///8,QF,Qantas,Qantas.png
        ///9,SK,SAS,Sas.png
        ///10,TK,Turkish Airlines,Turkish.png
        ///11,UA,United,United.png
        ///12,VA,Virgin Australia,Virgin.png.
        /// </summary>
        internal static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightNumber,DepartureAirportCode,ArrivalAirportCode,DepartureGate,ArrivalGate,DepartureTime,ArrivalTime,MaxPassengers,Status
        ///QF6424,ATH,BRN,D5,n/a,2022-05-19 11:30,2022-05-19 13:45,144,
        ///FR6758,CFU,DEB,B4,n/a,2022-05-19 11:57,2022-05-19 14:44,144,
        ///JL7162,BLL,SDR,B5,n/a,2022-05-19 12:26,2022-05-19 14:16,144,
        ///EK8293,BDS,CDG,D4,n/a,2022-05-19 12:52,2022-05-19 15:37,144,
        ///AC7719,VAA,AAL,B5,n/a,2022-05-19 13:15,2022-05-19 16:53,144,
        ///AC1492,MMX,PIK,B3,n/a,2022-05-19 13:44,2022-05-19 16:27,144,
        ///LH3167,TFN,TZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flights {
            get {
                return ResourceManager.GetString("Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationID,PassengerID,MaxLuggage,CheckedLuggage,SeatName,CheckedIn
        ///ZLDJBW,1,1,0,0,False
        ///KKWCIE,2,3,0,1,False
        ///NZQRXJ,3,2,0,2,False
        ///ENSRSK,4,1,0,3,False
        ///KZHVTY,5,1,0,4,False
        ///AOYGQY,6,3,0,5,False
        ///MTZMUK,7,1,0,6,False
        ///QDFUYN,8,3,0,7,False
        ///PXAYPX,9,1,0,8,False
        ///ZHNJLW,10,2,0,9,False
        ///TBBCWN,11,1,0,10,False
        ///DECWUV,12,1,0,11,False
        ///GUEXMG,13,1,0,12,False
        ///DOPYGW,14,2,0,13,False
        ///NLCFKY,15,3,0,14,False
        ///WESKRA,16,1,0,15,False
        ///YEKRQU,17,3,0,16,False
        ///RFFDEV,18,3,0,17,False
        ///ORPHXI,19,3,0,18,False
        ///OLS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PassengerReservations {
            get {
                return ResourceManager.GetString("PassengerReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassengerID,FirstName,LastName,Telephone,Email,Birthday
        ///0,John,Mccann,73737413,joh.mcc@hotmail.dk,1968-05-19
        ///1,Nia,Klein,52125082,nia.kle@gmail.com,1971-02-25
        ///2,Muhammad,Griffin,58506010,muh.gri@hotmail.com,1953-01-08
        ///3,Maya,Reyes,88155072,may.rey@gmail.com,2005-08-29
        ///4,Eden,Kirby,55734867,ede.kir@hotmail.dk,1951-12-02
        ///5,Gwendolyn,Boone,68402400,gwe.boo@hotmail.com,2001-04-17
        ///6,Denver,Vaughn,76748474,den.vau@yahoo.dk,1956-09-20
        ///7,Ryleigh,Franklin,67171657,ryl.fra@gmail.com,1996-01-29
        ///8,Kareem,Mcgee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Passengers {
            get {
                return ResourceManager.GetString("Passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationID,FlightNumber
        ///ZLDJBW,QF6424
        ///KKWCIE,QF6424
        ///NZQRXJ,QF6424
        ///ENSRSK,QF6424
        ///KZHVTY,QF6424
        ///AOYGQY,QF6424
        ///MTZMUK,QF6424
        ///QDFUYN,QF6424
        ///PXAYPX,QF6424
        ///ZHNJLW,QF6424
        ///TBBCWN,QF6424
        ///DECWUV,QF6424
        ///GUEXMG,QF6424
        ///DOPYGW,QF6424
        ///NLCFKY,QF6424
        ///WESKRA,QF6424
        ///YEKRQU,QF6424
        ///RFFDEV,QF6424
        ///ORPHXI,QF6424
        ///OLSUDT,QF6424
        ///YUXVPW,QF6424
        ///MXZJMT,QF6424
        ///IAKWPI,QF6424
        ///CZLFHT,QF6424
        ///FMJBGC,QF6424
        ///LXKICO,QF6424
        ///FHBKHY,QF6424
        ///NBCEOH,QF6424
        ///OUDKMJ,QF6424
        ///MOQLZA,QF6424
        ///DBIJTX,QF6424
        ///PWMPNU,QF6424
        ///TPJH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
    }
}
